/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_knight_jone_mySuperDemo_ndk_NDKTools */

#ifndef _Included_com_knight_jone_mySuperDemo_ndk_NDKTools
#define _Included_com_knight_jone_mySuperDemo_ndk_NDKTools
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_knight_jone_mySuperDemo_ndk_NDKTools
 * Method:    getStringFromNDK
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_knight_jone_mySuperDemo_ndk_NDKTools_getStringFromNDK
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
